apiVersion: v1
kind: Service
metadata:
  name: stats-api
  namespace: website
  labels:
    app: stats-api
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: stats-api